### ISSUE TITLE
Windows reporting is incorrect?

### ISSUE THREAD

**Issue by chrisdone** [corsis/clock#17]
Discovered [here](http://www.reddit.com/r/haskell/comments/2ri3ph/measuring_duration_in_haskell/cng894c?context=5).

It seems that the following program
``` haskell
{-# LANGUAGE OverloadedStrings #-}
import Control.Exception
import Formatting
import Formatting.Clock
import System.Clock
main =
  do start <- getTime Monotonic
     evaluate (sum [1 .. 1000000])
     end <- getTime Monotonic
     fprint (timeSpecs % "\n") start end
     print start
     print end
```
yields
``` haskell
14230228015319.42 d
TimeSpec {sec = 2182353207576363848, nsec = 0}
TimeSpec {sec = 3411844908099961672, nsec = 0}
```
Note that the nanoseconds field is empty, and the `sec` fields appear to be populated by the nanoseconds data. This is quite different from the Linux result:

``` haskell
295.43 ms
TimeSpec {sec = 3016732, nsec = 112561985}
TimeSpec {sec = 3016732, nsec = 407989679}
```

The difference between the two `sec` fields should be `0`. The only differing fields should be the nanoseconds, which should differ by a few hundred milliseconds. I don't have a means to test any Windows code, but I'd appreciate anyone looking into this and fixing it. It also looks like this number is only a few places from hitting `maxBound :: Int`, which is also an issue.

**Comment by compters** [comment]
I'm no expert on the Win32 api (or C for that matter) but I managed to get the library working by changing a type in the Storable instance for TimeSpec from a time_t to a long, see this commit
https://github.com/compters/clock/commit/b4607e67a53de82507a88e74d4268c374dd07def. I'm unaware if changing this structure would impact older or 32 bit versions of Windows though?

**Comment by chrisdone** [comment]
Haven't the foggiest; would appreciate other Windows users to chime in.

**Comment by kuznero** [comment]
Have `nsec = 0` as well on Window. Though, there is another inconsistency with getting monolithic time  with GHC, x64.

```haskell
import Data.Int
import System.Clock

main = go
  where
    go = do
        print =<< (fmap sec) (getTime Monotonic)
        go
```

This program yields following:

```
1316474555023488962
1328738189892122562
1342608181184165826
1355660006976124866
1368367990571268034
1380996624645617602
1393279659881527234
1405308780945864642
1417822803817920450
1432294073351534530
1445673867141183426
1458142045532321730
1470470925249148866
1482711637877323714
1494996434049824706
1507226568173549506
1520703346619709378
1533162707442988994
1534363502989539266
```

In addition this is what I observe in GHCi (again x64 version of GHC on Windows 8.1):

```plain
λ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> import System.Clock
Prelude System.Clock> getTime Monotonic
Loading package clock-0.4.1.3 ... linking ... <interactive>: warning: GetSystemTimeAsFileTime from kernel32 is linked in
stead of __imp_GetSystemTimeAsFileTime
<interactive>: warning: GetProcessTimes from kernel32 is linked instead of __imp_GetProcessTimes
<interactive>: warning: GetCurrentThread from kernel32 is linked instead of __imp_GetCurrentThread
<interactive>: warning: GetThreadTimes from kernel32 is linked instead of __imp_GetThreadTimes
done.
TimeSpec {sec = 4248233228571508837, nsec = 0}
Prelude System.Clock> getTime Monotonic
TimeSpec {sec = 1426136683681939559, nsec = 0}
Prelude System.Clock> getTime Monotonic
TimeSpec {sec = 1766616161623212136, nsec = 0}
Prelude System.Clock>
```

**Comment by phaazon** [comment]
I have the same issue. Something might be wrong around there! :)

**Comment by phaazon** [comment]
Bump. Hackage still not affected, even after several emails to @cetinsert. May he make me a maintainer on hackage, pretty please? :)

**Comment by cetinsert** [comment]
Sorry for the inexcusable deal people. @phaazon how can I make someone a maintainer?

**Comment by cetinsert** [comment]
@phaazon never mind. found out by myself. what is your hackage user name?

**Comment by cetinsert** [comment]
@phaazon @chrisdone @compters @kuznero @puffnfresh clock-0.4.2.0 just uploaded to hackage. Please confirm it fixes your issues.

**Comment by phaazon** [comment]
Thank you for the upload @cetinsert :) Fixed for me.
