### ISSUE TITLE
Getting time in one integral value

### ISSUE THREAD

**Issue by chrisdone** [corsis/clock#18]
I note that every use I have googled so far of this library end up converting the value to one integral value:

* [slingspace](https://github.com/Eelis/slingspace/blob/master/src/Util.hs#L61)

``` haskell
timeSpecAsNanoSecs :: TimeSpec → Integer
timeSpecAsNanoSecs t = toInteger (sec t) * 1000000000 + toInteger (nsec t)
```

* [This blog post](http://paulkoerbitz.de/posts/Efficient-Quicksort-in-Haskell.html)

``` haskell
    loop nRuns (do nums' <- V.thaw nums
                   start <- getTime ProcessCPUTime
                   qsort nums'
                   time <- getTime ProcessCPUTime - start
                   putStrLn $ show $ fromIntegral (sec time) +
                                     ((fromIntegral $ nsec time) / 1000000000))
```

* [marquise-haskell](https://github.com/anchor/marquise-haskell/blob/master/src/System/Marquise.hs#L124)
``` haskell
timeNow :: Marquise Word64
timeNow = liftM fromIntegral $ liftIO $
    (+) <$> ((1000000000*) . sec) <*> nsec <$> getTime Realtime
```

* My own [formatting package](https://github.com/chrisdone/formatting/blob/126a1aaf1cbe8d065c0e3399c58a017bd0afb3f8/src/Formatting/Clock.hs#L38)
``` haskell
a1 = (fromIntegral s1 * 10 ^ 9) + fromIntegral n1
```

Maybe a function to get this would be handy?

**Comment by osa1** [comment]
Came here to ask for this... Maybe we should create a `clock-utils` package.

**Comment by cetinsert** [comment]
@chrisdone @osa1 added `timeSpecAsNanoSecs` in 0.4.3.0
