### ISSUE TITLE
TimeSpec formats

### ISSUE THREAD

**Issue by phaazon** [corsis/clock#20]
Currently, `TimeSpec` uses two unboxed and unpacked `Int64`. I think `Int64` should be replaced by `Int` since it’s exactly the same thing. I might be wrong, but isn’t `Int` supposed to be 8 bytes long?

**Comment by cetinsert** [comment]
Is this still an issue with `clock-0.4.3.0`?

**Comment by phaazon** [comment]
You really should provide a `CHANGELOG`, I have no idea what came up with `clock-0.4.3.0`. Let me dig in.

**Comment by phaazon** [comment]
Ok, still `Int64`. It’s not really an issue, but it’s unconvenient to use when we need to handle `sec` and `nsec`. Anyways, you can close the issue if no one else complains about that. Since we have the function `timeSpecAsNanoSecs`, I don’t need to use the former functions.

**Comment by cetinsert** [comment]
@phaazon Thanks, I will see to this `CHANGELOG` thing; can you point me to a hackage package that does it right and simple?

**Comment by phaazon** [comment]
My [monad-journal](https://hackage.haskell.org/package/monad-journal) package is pretty clair with that :)
