### ISSUE TITLE
Clock 0.4.4.0 fails to install (GHC 7.8.3)

### ISSUE THREAD

**Issue by chwthewke** [corsis/clock#21]
The error is shown further down, and would seem to indicate some AMP-related backwards incompatibility. Do you consider supporting GHC 7.8 reasonable, and if so, can this be fixed? (Not being a lib dev, I have no idea how inconvenient that would be, I vaguely gather that CPP might be involved, but that's about it, thus the candid question.)

Thanks,

Error message:

    [1 of 1] Compiling System.Clock     ( dist\dist-sandbox-d421a81f\build\System\Clock.hs, dist\dist-sandbox-d421a81f\build\System\Clock.o )
    
    SystemClock.hsc:151:9: Not in scope: `<$>'
    
    SystemClock.hsc:152:9: Not in scope: `<*>'
    cabal.exe: Error: some packages failed to install:
    clock-0.4.4.0 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by fegu** [comment]
I came her to report this as well. Windosw x64 GHC 7.8.3.

**Comment by joeyh** [comment]
Ditto.

BTW, the cabal file has the issue tracker url as http://corsis.github.com/clock/issues which was a 404 when I tried it.

**Comment by cetinsert** [comment]
@fegu @joeyh @chwthewke addressed all issues mentioned in `clock-0.4.5.0`.
