### ISSUE TITLE
version 0.4.6 not found on this repo

### ISSUE THREAD

**Issue by damiencourousse** [corsis/clock#26]
hello,

This repository does not seem to be uptodate with http://hackage.haskell.org. Please could you update? Can't find version 0.4.6.0 here, while this place is referred as the source repository on hackage.

best regards,
Damien

**Comment by cetinsert** [comment]
http://hackage.haskell.org/package/clock-0.4.6.0 !?

**Comment by damiencourousse** [comment]
Yes, but the release info is not found in _this_ repo (https://github.com/corsis/clock), whereas it is documented in hackage as the official source repository.
Release 0.4.5.0 is not tagged, but it is documented in the commit messages, but release 0.4.6.0 is neither tagged nor documented in the commit messages. 

Did I miss something ? This practice looks unusual to me, hence the issue report.

best regards,
Damien

```
$ git clone https://github.com/corsis/clock.git
Clonage dans 'clock'...
remote: Counting objects: 207, done.
remote: Total 207 (delta 0), reused 0 (delta 0), pack-reused 207
Réception d'objets: 100% (207/207), 138.84 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (77/77), fait.
Vérification de la connectivité... fait.
$ cd clock/
$ git tag -l
0.3
0.3x
0.4
0.4.0.1
$ git log | grep 0.4.5.0
    0.4.5.0
$ git log | grep 0.4.6.0
$ 
```

**Comment by cetinsert** [comment]
Oh, I see. Yeah I will stick to using tags more consistently from now on. Hope this one helps https://github.com/corsis/clock/releases/tag/0.4.6.0 you now!
