### ISSUE TITLE
Bug: abs (TimeSpec 0 1) == TimeSpec 0 0

### ISSUE THREAD

**Issue by wereHamster** [corsis/clock#28]
```haskell
abs (TimeSpec 0 1)    == TimeSpec 0 0
abs (TimeSpec 0 (-1)) == TimeSpec 0 0
```

That doesn't look correct. Where are the tests?

**Comment by cetinsert** [comment]
How about? I haven't written the `Num TimeSpec` instance btw.

```haskell
abs (TimeSpec a b)    == TimeSpec (abs a) (abs b)
```

**Comment by wereHamster** [comment]
That doesn't look like a correct implementation, it would give the wrong result when given `TimeSpec -1 1000000000`.

**Comment by cetinsert** [comment]
@wereHamster what would be a correct one then?

**Comment by wereHamster** [comment]
`TimeSpec (-1) 1000000000` normalized is `TimeSpec 0 0`. The absolute value of that is 0. However your implementation would give me 2 seconds.

**Comment by wereHamster** [comment]
A correct implementation, albeit maybe a slow one, is:

```haskell
    abs = fromIntegral . abs . toInteger
```

(assuming there is an `Integral TimeSpec` instance).
