### ISSUE TITLE
Access to coarse clocks

### ISSUE THREAD

**Issue by gregorycollins** [corsis/clock#30]
Hi,

A feature request: Linux has a couple of clocks `CLOCK_REALTIME_COARSE` and `CLOCK_MONOTONIC_COARSE` that trade off clock accuracy for speed of `clock_gettime()`. A few years ago I mocked up a quick benchmark showing that the coarse clocks are almost twice as fast as the realtime ones: https://gist.github.com/gregorycollins/3634708

**Comment by cetinsert** [comment]
Nice suggestion! If anyone has the time to commit a patch which adds this for Linux, it would be appreciated. Otherwise I cannot tell when I might add this support myself.

**Comment by cetinsert** [comment]
Implemented in [New Linux-specific Clocks: MonotonicRaw, Boottime, MonotonicCoarse, RealtimeCoarse](https://github.com/corsis/clock/commit/c560d1c30eb88685232030a3953ccc919ba5fa50#diff-311597378c63fcf6b8431111b68ad606R78) and released in `0.6.0` on hackage.

**Comment by gregorycollins** [comment]
Great! Glad you had time to get around to this, thank you.
