### ISSUE TITLE
Document behavior of monotonic clock during suspension (sleep)

### ISSUE THREAD

**Issue by 3noch** [corsis/clock#31]
I cannot determine from the documentation whether or not the monotonic clock counts during suspension. I know that Window's `GetTickCount` _does_ tick during sleep. I'm not sure about other OSes.

**Comment by cetinsert** [comment]
I think people should just refer to the respective OS's own documentation. If someone posts a table for each OS, I could update the package.

**Comment by 3noch** [comment]
Yes that's of course possible, but requires that one dig open your source code and figure out which OS API is being used for each platform. At the very least some documentation noting that the behavior may not be consistent across platforms could be enough. It communicates both that you did not overlook the question and that you are not willing to provide an answer.

**Comment by cetinsert** [comment]
@3noch please review, [New Linux-specific Clocks: MonotonicRaw, Boottime, MonotonicCoarse, RealtimeCoarse](https://github.com/corsis/clock/commit/c560d1c30eb88685232030a3953ccc919ba5fa50#diff-311597378c63fcf6b8431111b68ad606R87) with regards to CLOCK_BOOTTIME.

Now we have a suspend-aware `Clock.Monotonic`implementation on Windows (as you claim, using `GetTickCount`) and a suspend-unaware one on Linux, backed by `Clock.Boottime` which is again suspend-aware o__O!

**Comment by 3noch** [comment]
@cetinsert Great work! I am not familiar enough with Linux to comment about correctness, but this is a great addition. Have you thought of introducing the difference between "suspend-aware" and "suspend-unaware" clocks somewhere early in the docs (like the intro section, perhaps)?

**Comment by cetinsert** [comment]
@3noch I am still reading into this whole suspend-awareness thing. Once done, I will amend the documentation.

Now though, we have an OS-dependent implementation difference, `CLOCK_MONOTONIC` is not suspend-aware on Linux but is so on Windows!

We provide `CLOCK_BOOTTIME` on Linux but that would force people to `#ifdef` their code perhaps unnecessarily.

```
Today

C/O L W
M   U A
B   A X

C:lock O:S L:inux W:indows
M:onotonic Suspend-A:ware Suspend-U:naware
B:oottime  X:missing

---

Desired?

C/O L W
M   U U1
B   A A2

```
2: remap current Windows implementation of `Clock.Monotonic` to `Clock.Boottime` and expose `Clock.Boottime` on Windows

[1: new implementation using QpcBias](http://stackoverflow.com/a/24942907/112882)

```C
#include <nt.h>
#include <ntrtl.h>
#include <nturtl.h>

LONGLONG suspendTime, uiTime1, uiTime2;
QueryUnbiasedInterruptTime((ULONGLONG*)&uiTime1);
uiTime1 -= USER_SHARED_DATA->QpcBias;  // subtract off the suspend bias
```

**Comment by 3noch** [comment]
Very much agreed. Having significant differences across OSes is certainly not ideal. I really like the idea of pulling in `QueryUnbiasedInterruptTime` to give Windows an equivalent to Linux's monotonic clock, and mapping Windows' `GetTickCount` to the boottime clock.

**Comment by 3noch** [comment]
I'm curious what the reasoning for "wontfix" is.

**Comment by cetinsert** [comment]
Simply no time and no immediate personal need to look into this in 2016 and get reliable findings I could not only document but stand behind. I would be welcome to merge any pull requests without delay though.

**Comment by 3noch** [comment]
@cetinsert Thanks for reopening. I'm not sure can offer a fix soon either, but it's good to have some record of this.

**Comment by ndmitchell** [comment]
@cetinsert - I think a tag for you saying you won't fix is valuable, but I think won't fix sends the wrong message. I just add the label "help required" for tasks that I won't fix but that I'd be happy to accept pull requests on.

**Comment by cetinsert** [comment]
@ndmitchell just addressed the labeling!

**Comment by cetinsert** [comment]
Anyone with more, recent experience on this willing on to improve the documentation?

**Comment by cetinsert** [comment]
I have just reviewed https://github.com/corsis/clock/blob/master/System/Clock.hsc and it documents suspend-awareness of various clocks in context quite well. Closing this issue. Re-open if you want modifications to the existing documentation.
