### ISSUE TITLE
(*) for TimeSpec doesn't follow the ring laws

### ISSUE THREAD

**Issue by lfairy** [corsis/clock#32]
```haskell
ghci> let t = TimeSpec 1 0
ghci> 1 * t == t
False
```

This issue has caused a bug in my own code. I was trying to construct a `TimeSpec` like this:

```haskell
delay :: TimeSpec
delay = 600 * 1000 * 1000
```

But because of the `*` implementation, `delay` became zero instead.

The problem is that `fromInteger` uses nanoseconds, while `*` uses seconds. This inconsistency leads to strange behavior when literals (which use `fromInteger`) and multiplication appear together.

I recommend removing `*` completely, replacing it with a call to `error`.

**Comment by cetinsert** [comment]
Removed `fromInteger : Integer -> TimeSpec` as this was introduced by a third party and I cannot maintain it, users need to be explicit in their conversions from now on.
https://github.com/corsis/clock/commit/0fa95488517433cf64100786ed10fd2bb40353b9#diff-311597378c63fcf6b8431111b68ad606R192

**Comment by juhp** [comment]
@cetinsert could you explain why?

**Comment by lfairy** [comment]
@cetinsert Another solution would be to deprecate the `Num` instance, and replace it with `addTimeSpec`/`subTimeSpec`/`fromSeconds` functions. That should cover the majority of use cases while still being correct.

**Comment by cetinsert** [comment]
How do I deprecate `Num` instance without breaking people's code?

**Comment by bergmark** [comment]
It's not possible, but assuming people have upper bounds on this package according to the PVP code won't just break. There was recently a proposal to allow adding warnings when using specific instances, but I'm not sure if it gained traction. It was also meant for a different use case, e.g. to prevent you from using the Traversable (a,) instance.
