### ISSUE TITLE
let x = TimeSpec 1 0 in 2*x == x+x

### ISSUE THREAD

**Issue by afcady** [corsis/clock#33]
It's False.

**Comment by cetinsert** [comment]
[Removed `fromInteger : Integer -> TimeSpec`](https://github.com/corsis/clock/commit/0fa95488517433cf64100786ed10fd2bb40353b9#diff-311597378c63fcf6b8431111b68ad606R192) as this was introduced by a third party and I cannot maintain it, users need to be explicit in their conversions from now on.

**Comment by juhp** [comment]
Could you explain why can't you maintain fromInteger?
