### ISSUE TITLE
Missing fromInteger definition?

### ISSUE THREAD

**Issue by mightybyte** [corsis/clock#36]
Hi guys,

We've been having some mysterious runtime failures (reported by @imalsogreg) with Snap applications [1].  After some investigation it looks like this problem only happens when building against clock >= 0.5.2 and only on some OSs.  However, everything works fine with clock-0.5.1.  After looking at the changes between 0.5.1 and 0.5.2 I discovered this line:

https://github.com/corsis/clock/blob/master/System/Clock.hsc#L234

I strongly suspect that this missing `fromInteger` function is causing our crashes.  Could you put that function back in?  If not, then maybe TimeSpec should not export a Num instance at all.

[1] https://github.com/snapframework/snap-server/issues/82

**Comment by imalsogreg** [comment]
@mightybyte's Suspicion about line L234 is correct - uncommenting this results in working servers, leaving it commented out results in non-working servers. The OS is Ubuntu 14.04, the failure is consistent across machines.

**Comment by k-bx** [comment]
@cetinsert please take a look at this as latest clock is included in stackage, so it might soon start hitting more people

**Comment by hvr** [comment]
What as the motivation 0fa95488517433cf64100786ed10fd2bb40353b9? Not defining `fromInteger` (or any other mandatory method) is quite nasty as the compiler has little way to warn you at use-sites that it'll run into a bottom value.

**Comment by k-bx** [comment]
No idea. Either you don't provide a `Num` or you provide `fromInteger`, otherwise this is just bad.

**Comment by imalsogreg** [comment]
@cetinsert Heya. Any updates on this, or can I help? Thanks!

**Comment by bergmark** [comment]
We are planning to perform a non-maintainer upload in two weeks if the maintainer is not available, tracked in https://github.com/haskell-infra/hackage-trustees/issues/63

It sounds like the least intrusive patch is re-introducing `fromInteger`, do you agree?

**Comment by k-bx** [comment]
Yup.

**Comment by mightybyte** [comment]
Agreed.

**Comment by cetinsert** [comment]
`fromInteger` has been reintroduced in 0.7.1.1, package uploaded to hackage.

Now how could we address: issue #32 and #33 ?
