### ISSUE TITLE
Why does clock's versioning scheme deviate from the PVP?

### ISSUE THREAD

**Issue by hvr** [corsis/clock#39]
The http://hackage.haskell.org frontpage states:

> Guidelines for Hackage Packages:
> - All packages should follow the Package Versioning Policy (PVP).
>   ...

However, `clock` seems to deviate from this guideline subtly by declaring its own versioning scheme in the package-description:

> Version Scheme
> Major-R-ewrite . New-F-unctionality . I-mprovementAndBugFixes . P-ackagingOnly

but I fail to see the motivation for this. Is there a reason for this deviation from the Hackage guidelines? Or is the package description out of date  and `clock` does indeed adhere the PVP scheme now?

**Comment by cetinsert** [comment]
I am not sure what is better in the PVP to motivate a change except for the sake of going with the convention. If you would not mind making a better a case for it though, you are most welcome.

**Comment by imalsogreg** [comment]
In my case, I use the PVP to choose upper bounds for my dependencies. I assume that bugfixes and non-breaking additions to the API, reflected in minor version bumps, are allowable for my dependencies.

On the flip side, I assume that dependencies don't have any changes that break my code at either compiletime or runtime when the major version is the same. This convention is how my dependency's authors communicate to me when I have to look through my code and consider changing my calls out to that dependency (and when I don't have to). There are very many dependencies - so this convention is the heuristic that makes it possible to keep up.

I believe that this convention is very common for people with long-term projects. We use the PVP for reasoning about the validity of our use of our dependencies. This assurance is what lets library authors fearlessly make a semantic change to their library - they know that as long as they give a major version bump, they are not hurting anyone who uses the library.

So when a library author makes a semantic change, but does not bump major version number, all the users can suffer.
