### ISSUE TITLE
Add a `diff` and `time` functions

### ISSUE THREAD

**Issue by jfischoff** [corsis/clock#42]
I almost always use `clock` to time Haskell IO actions. I would like it these functions lived in this package.

``` haskell

elapsedTime :: TimeSpec -> IO a -> IO (a, Double)
elapsedTime timeSpec action = do
  startTime <- getTime timeSpec 
  r <- action
  endTime   <- getTime timeSpec 

  let !result = diffTime endTime startTime

  return (r, result)

diffTime :: TimeSpec -> TimeSpec -> Double
diffTime end start = (* 1e-9) $ fromIntegral $ toNanoSecs end - toNanoSecs  start
```

**Comment by sjakobi** [comment]
I think you mean `elapsedTime :: Clock -> IO a -> IO (a, Double)`.

I'd prefer the following type though as I only seldomly work directly in `IO`:

```
elapsedTime :: MonadIO m => Clock -> m a -> m (a, TimeSpec)
```

The `diffTime` function doesn't look too useful as there's already `diffTimeSpec :: TimeSpec -> TimeSpec -> TimeSpec` and users may want to convert to a different unit than seconds.

**Comment by jfischoff** [comment]
On Wed, Aug 24, 2016 at 1:08 PM, Simon Jakobi <notifications@github.com>
wrote:

> I think you mean elapsedTime :: Clock -> IO a -> IO (a, Double).
>
> I'd prefer the following type though as I only seldomly work directly in
> IO:
>
> elapsedTime :: MonadIO m => Clock -> m a -> m (a, TimeSpec)
>
> Fine, not sure if you want the dependency and in this case `liftIO` would
work. Your call.

>  The diffTime function doesn't look too useful as there's already diffTimeSpec
> :: TimeSpec -> TimeSpec -> TimeSpec and users may want to convert to a
> different unit than seconds.
>
Fair.
