### ISSUE TITLE
clock cannot be cross-compiled

### ISSUE THREAD

**Issue by iphydf** [corsis/clock#45]
This patch makes it work: https://github.com/TokTok/hs-toxcore/blob/3dcca82905396780b8eb41936c3a239fb55e5e3a/android/patches/hs-clock-ffi.patch

This solution is not portable (`__alignof__` is a gcc extension). It might be portable enough. If not, you may be able to do something like that with conditional compilation.

**Comment by x1ddos** [comment]
This should be fixed by #44.
