### ISSUE TITLE
Provide a fallback implementation on ghcjs

### ISSUE THREAD

**Issue by feuerbach** [corsis/clock#46]
Hi,

I use clock in [tasty](https://github.com/feuerbach/tasty) to measure the duration of each test.

However, this prevents tasty from building on ghcjs.

I have a [pull request](https://github.com/feuerbach/tasty/pull/150) that replaces clock functions with `Data.Time` functions when compiled by ghcjs.

But I think that this logic really belongs to the clock package itself. This way all users of clock can benefit from a more portable lirbary.

If needed, I can try to prepare a PR.

What do you think?

**Comment by cetinsert** [comment]
Please send a PR!

**Comment by cetinsert** [comment]
@feuerbach still waiting on the PR.

**Comment by feuerbach** [comment]
Hey @cetinsert, I don't anticipate that I'll have the time to work on this in the nearest future, sorry.

**Comment by cetinsert** [comment]
Closing as nobody is available to work on this request.
