### ISSUE TITLE
clock can not be cross-compiled again

### ISSUE THREAD

**Issue by nek0** [corsis/clock#48]
Hi. When trying to crosscompile clock to armhf i encounter following error:

```
System/Clock.hsc:44 directive let cannot be handled in cross-compilation mode
```

Can you please fix this?

Thank you for your time.

**Comment by cetinsert** [comment]
I don't have a build environment ready for this type of work.

Can you provide me precise instructions to reproduce the above message using 64-bit Linux / Windows / OS X or modify the affected line(s) in source file(s) in a way that eliminates the error and send the result as a pull request?

**Comment by nek0** [comment]
I poked around a little. It compiles, when you comment the lines 44 - 46 in `System/Clock.hsc` out, but that might break compatibility with older compilers.

**Comment by nh2** [comment]
I don't understand why this happens. In https://github.com/corsis/clock/commit/f7fe4fb5691d56c342e6fbf5a99c121ab24a6b41, the problematic code was put in an `#if __GLASGOW_HASKELL__ < 800` so it shouldn't trigger.

But it triggers during my cross-compilation. Is `__GLASGOW_HASKELL__` set to something weird somehow?

**Comment by nh2** [comment]
Actually I don't have this problem at commit 00435ddf926b3603a3576d98e44763d165d2ec2c

**Comment by cetinsert** [comment]
@nh2 so what would be a fix?

**Comment by nh2** [comment]
@cetinsert It might just be that the version on Hackage is so old that doesn't have the fix, see #55.

So I suspect the fix would just making a new release.

**Comment by sboosali** [comment]
(@nh2 I saw this issue when building an Android application with `reflex-platform`, which did likely use an older version of `clock` as the package set was pinned to a few years ago. so this might indeed fix it, though I haven't tested it myself.)

**Comment by cetinsert** [comment]
@nh2 @sboosali @nek0 - new version of [`clock`](http://hackage.haskell.org/package/clock) has just been released on `hackage`!

Closing this issue tentatively, re-open if issues persist.

**Comment by sboosali** [comment]
thanks!

**Comment by nh2** [comment]
Thanks!
