### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by angerman** [corsis/clock#55]
Can we get a new `clock` release? It looks like (https://hackage.haskell.org/package/clock)
the last `0.7.2` release is from 2016.

And as noted elsewhere (#48), doesn't include the `hsc2hs` conditionals for cross compilation,
which means one needs to always use `clock` as a source import when cross compiling.

**Comment by quasicomputational** [comment]
I'd also appreciate a release, please. hpack's currently got no Windows CI because of the bug fixed in #52, and I suspect that that's not the only package in the same situation.

**Comment by sboosali** [comment]
any update?

**Comment by cetinsert** [comment]
@sboosali @quasicomputational @stevladimir @angerman @nh2 - waiting for my hackage uploader account to re-activated to upload.

**Comment by sboosali** [comment]
thank you for the update

**Comment by cetinsert** [comment]
@sboosali @quasicomputational @stevladimir @angerman @nh2 - just uploaded `0.8` - http://hackage.haskell.org/package/clock

**Comment by stevladimir** [comment]
Thanks
